---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    dockerfile: Dockerfile.centos6.j2
    groups:
      - molecule_hosts
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule_hosts:
        vars:
          aide_custom_rules:
            - name: FIPSR
              pattern: 'p+i+n+u+g+s+m+c+acl+selinux+xattrs+sha256'
            - name: ALLXTRAHASHES
              pattern: 'sha1+rmd160+sha256+sha512+tiger'
            - name: EVERYTHING
              pattern: 'R+ALLXTRAHASHES'
            - name: NORMAL
              pattern: sha256
            - name: DIR
              pattern: 'p+i+n+u+g+acl+selinux+xattrs'
            - name: PERMS
              pattern: 'p+u+g+acl+selinux+xattrs'
            - name: STATIC
              pattern: 'p+u+g+acl+selinux+xattrs+i+n+b+c+ftype'
            - name: LOG
              pattern: 'p+u+g+n+acl+selinux+ftype'
            - name: CONTENT
              pattern: 'sha256+ftype'
            - name: CONTENT_EX
              pattern: 'sha256+ftype+p+u+g+n+acl+selinux+xattrs'
            - name: DATAONLY
              pattern: 'p+n+u+g+s+acl+selinux+xattrs+sha256'
          aide_acls:
            - regexp: '/boot/'
              rule: CONTENT_EX
            - regexp: '/bin/'
              rule: CONTENT_EX
            - regexp: '/sbin/'
              rule: CONTENT_EX
            - regexp: '/lib/'
              rule: CONTENT_EX
            - regexp: '/lib64/'
              rule: CONTENT_EX
            - regexp: '/opt/'
              rule: CONTENT
            - regexp: '/proc/'
              rule: 'absent'
            - regexp: '/root/\..*'
              rule: PERMS
            - regexp: '/root/'
              rule: CONTENT_EX
            - regexp: '/usr/src/'
              rule: 'absent'
            - regexp: '/usr/tmp/'
              rule: 'absent'
            - regexp: '/usr/'
              rule: CONTENT_EX
            - regexp: '/etc/'
              rule: CONTENT_EX
            - regexp: '/var/log/'
              rule: 'absent'
            - regexp: '/var/run'
              rule: 'absent'
            - regexp: '/var/'
              rule: 'absent'
      molecule_hosts_centos_6:
        vars:
          aide_custom_rules:
            - name: NORMAL
              pattern: 'R+rmd160+sha256'
          aide_acls:
            - regexp: '/boot/'
              rule: NORMAL
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
