---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Read AIDE config
      command: /usr/sbin/aide -D
      changed_when: no
      register: aide_read_config_result

    - name: Check read database
      stat:
        path: /var/lib/aide/aide.db.gz
      register: aide_read_database_result

    - name: Check cron file
      stat:
        path: "/etc/cron.d/aide"
      register: aide_read_cron_result

    - name: Assert all post conditions
      assert:
        that:
          - aide_read_config_result.stdout is not search("Configuration error")
          - aide_read_database_result.stat.exists
          - aide_read_cron_result.stat.exists
